-- Phase 2 Plan 6 Task 5: sdtm_source schema + 5 fmt_<domain> tables.
-- Column shapes match SDTM v3.4 IG. Primary keys emerge from USUBJID +
-- domain-specific sequence variables (--SEQ); we use surrogate BIGSERIAL
-- here because pyreadstat-loaded XPTs lack sequence-aware uniqueness.

CREATE SCHEMA IF NOT EXISTS sdtm_source;

CREATE TABLE IF NOT EXISTS sdtm_source.fmt_dm (
    id BIGSERIAL PRIMARY KEY,
    STUDYID VARCHAR(50),
    USUBJID VARCHAR(50) NOT NULL,
    SUBJID VARCHAR(50),
    RFSTDTC VARCHAR(20),
    RFENDTC VARCHAR(20),
    RFXSTDTC VARCHAR(20),
    RFXENDTC VARCHAR(20),
    RFICDTC VARCHAR(20),
    RFPENDTC VARCHAR(20),
    DTHDTC VARCHAR(20),
    DTHFL VARCHAR(2),
    SITEID VARCHAR(20),
    AGE NUMERIC,
    AGEU VARCHAR(20),
    SEX VARCHAR(2),
    RACE VARCHAR(80),
    ETHNIC VARCHAR(80),
    ARMCD VARCHAR(20),
    ARM VARCHAR(80),
    ACTARMCD VARCHAR(20),
    ACTARM VARCHAR(80),
    COUNTRY VARCHAR(80)
);

CREATE TABLE IF NOT EXISTS sdtm_source.fmt_ae (
    id BIGSERIAL PRIMARY KEY,
    STUDYID VARCHAR(50),
    USUBJID VARCHAR(50) NOT NULL,
    AESEQ NUMERIC,
    AETERM VARCHAR(255),
    AEDECOD VARCHAR(255),
    AEBODSYS VARCHAR(255),
    AESEV VARCHAR(20),
    AESER VARCHAR(2),
    AEACN VARCHAR(50),
    AEREL VARCHAR(50),
    AEOUT VARCHAR(50),
    AESTDTC VARCHAR(20),
    AEENDTC VARCHAR(20),
    AESTDY NUMERIC,
    AEENDY NUMERIC
);

CREATE TABLE IF NOT EXISTS sdtm_source.fmt_cm (
    id BIGSERIAL PRIMARY KEY,
    STUDYID VARCHAR(50),
    USUBJID VARCHAR(50) NOT NULL,
    CMSEQ NUMERIC,
    CMTRT VARCHAR(255),
    CMDECOD VARCHAR(255),
    CMINDC VARCHAR(255),
    CMDOSE NUMERIC,
    CMDOSU VARCHAR(20),
    CMDOSFRM VARCHAR(50),
    CMDOSFRQ VARCHAR(50),
    CMROUTE VARCHAR(50),
    CMSTDTC VARCHAR(20),
    CMENDTC VARCHAR(20),
    CMSTDY NUMERIC,
    CMENDY NUMERIC
);

CREATE TABLE IF NOT EXISTS sdtm_source.fmt_vs (
    id BIGSERIAL PRIMARY KEY,
    STUDYID VARCHAR(50),
    USUBJID VARCHAR(50) NOT NULL,
    VSSEQ NUMERIC,
    VSTESTCD VARCHAR(20),
    VSTEST VARCHAR(255),
    VSPOS VARCHAR(20),
    VSORRES VARCHAR(50),
    VSORRESU VARCHAR(20),
    VSSTRESC VARCHAR(50),
    VSSTRESN NUMERIC,
    VSSTRESU VARCHAR(20),
    VSDTC VARCHAR(20),
    VSDY NUMERIC,
    VSTPT VARCHAR(50),
    VSTPTNUM NUMERIC
);

CREATE TABLE IF NOT EXISTS sdtm_source.fmt_lb (
    id BIGSERIAL PRIMARY KEY,
    STUDYID VARCHAR(50),
    USUBJID VARCHAR(50) NOT NULL,
    LBSEQ NUMERIC,
    LBTESTCD VARCHAR(20),
    LBTEST VARCHAR(255),
    LBCAT VARCHAR(50),
    LBORRES VARCHAR(50),
    LBORRESU VARCHAR(20),
    LBORNRLO VARCHAR(50),
    LBORNRHI VARCHAR(50),
    LBSTRESC VARCHAR(50),
    LBSTRESN NUMERIC,
    LBSTRESU VARCHAR(20),
    LBSTNRLO NUMERIC,
    LBSTNRHI NUMERIC,
    LBNRIND VARCHAR(20),
    LBSTAT VARCHAR(20),
    LBDTC VARCHAR(20),
    LBDY NUMERIC
);
