checks:
  - name: person_yob_in_range
    table: person
    column: year_of_birth
    severity: error
    expected_pass: true
  - name: person_id_unique
    table: person
    column: person_id
    severity: error
    expected_pass: true
